# Todos os livros
GET http://localhost:5000/livros

###

# Livro por id
GET http://localhost:5000/livros/2

###

# Atualizar livro por ID
PUT http://localhost:5000/livros/3 HTTP/1.1
content-type: application/json

{
    "autor": "Habitos Gerais",
    "id": 3,
    "titulo": "James Clear"
}
###

# Criar livro
POST http://localhost:5000/livros HTTP/1.1
content-type: application/json

{
    "autor": "Eu mesmo",
    "id": 4,
    "titulo": "Um grande livro"
}
###

# Apagar livro por ID
DELETE http://localhost:5000/livros/2
